# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: License check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: mvn -N install
      run:
        mvn -N install
    - name: mvn install
      run:
        mvn install
    - name: get current dependencies
      run:
        mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=~/current_dependencies
        ls ~/current_dependencies  |egrep -v "^linkis" |sort  > ~/current_dependencies.txt
        
    - name: check third dependencies 
      run: |
        join -t : -o 1.1 2.1 -a2 ${{ github.workspace }}/tool/dependencies/known-dependencies.txt ~/current_dependencies.txt > ~/result.txt
        awk -F ":" '{if($1=="")print $2" is not in file known-dependencies.txt!"}' result.txt
